### ISSUE TITLE
Please use XDG compliant data path by _default_

### ISSUE THREAD

**Issue by z0rc** [RobertAudi/tsm#1]
Sorry for making this bold.

It isn't acceptable for freshly developed software to create dotfiles in `$HOME` nowadays. [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is more than decade old and is acknowledged industry standard.

Please use `$XDG_DATA_HOME/tmux-sessions`as **default** `$TSM_HOME` with proper fallback to `~/.local/share/tmux-sessions` if the `$XDG_DATA_HOME` isn't set. You may allow `~/.tmux-sessions` as a legacy location with warning asking user to move files to new location.

**Comment by RobertAudi** [comment]
Good point. The default value used for `$TSM_HOME` is actually "legacy code" present before this was turned into a plugin.
